stages:
  get_data:
    cmd: python scripts/data.py
    deps:
      - scripts/data.py
    params:
      - table
      - output_path
      - sslmode
    outs:
      - data/initial_data.csv
  fit_model:
    cmd: python scripts/fit.py
    deps:
      - data/initial_data.csv
      - scripts/fit.py
    params:
      - data.initial_data_path
      - data.model_path
      - split.test_size
      - split.random_state
      - model.iterations
      - model.learning_rate
      - model.depth
      - model.loss_function
      - model.random_state
      - model.verbose
    outs:
      - models/fitted_model.pkl
